- name: install dependencies
  hosts: all
  gather_facts: yes
  tasks:

    - name: install the latest version of epel-release
      yum:
       name: epel-release
       state: latest
      when:
       - ansible_distribution == "CentOS"
       - ansible_distribution_major_version == "7"

    - name: install multiple packages
      yum:
        name:  "{{ item }}"
        state: present
      with_items:
        - httpd
        - mod_ssl
        - mod_wsgi
        - phpmyadmin
        - proftpd
        - dovecot
        - postgresql-server
        - php
        - php-fpm
        - php-pdo
        - php-cli
        - php-pgsql
        - php-gd
        - php-xml
        - php-opcache
        - mariadb-server
        - rabbitmq-server
        - certbot
        - python-pika
        - postfix
        - mc
        - net-tools
        - mosh
        - git
        - psmisc
        - ftp
        - roundcubemail
        - screen
        #- php-mysqlnd

    - name: install multiple packages on centos 7+
      yum:
        name:  "{{ item }}"
        state: present
      with_items:
        - python34-virtualenv
        - python34-pika
        - python34-mysql
        - python34-pg8000
      when:
       - ansible_distribution == "CentOS"
       - ansible_distribution_major_version == "7"


    - name: install multiple packages on Fedora 27+
      yum:
        name:  "{{ item }}"
        state: present
      with_items:
        - python3-virtualenv
        - python3-pika
        - python3-mysql
        - python3-pg8000
      when:
       - ansible_distribution == "Fedora"
       - ansible_distribution_major_version >= "27"

    - name: upgrade all packages
      yum:
       name: '*'
       state: latest
