#!/usr/bin/bash

servicos=(linux-backend-apache linux-backend-database-mysql linux-backend-mail linux-backend-proftpd)

for s in "${servicos[@]}"
do
    echo "Setting up ${s}\n"
    systemctl enable $s
    systemctl start $s
done

mkdir -p /var/lib/yawep/data
chmod 1777 /var/lib/yawep/data
chown apache:apache /var/lib/yawep/data -R

#create default user
curl -i -u x:x -X POST -H "Content-Type: application/json" -d '{"email":"itamar1@ispbrasil.com.br","username":"x","password":"x"}' https://painel.ispbrasil.com.br/api/users
